export const CONTACT_ITEMS: Partial<Queries.ContentfulContactItem>[] = [
  {
    title: "Phone",
    iconName: "HiPhoneArrowUpRight",
    url: "tel:+972528717475",
    color: "#00a8e8",
    tooltip: "Give me a call - 0528717475",
  },
  {
    title: "WhatsApp",
    iconName: "SiWhatsapp",
    url: "https://api.whatsapp.com/send?phone=972528717475",
    color: "#25d366",
  },
  {
    title: "Telegram",
    iconName: "SiTelegram",
    url: "https://t.me/deddy_xyz",
    color: "#0088cc",
  },
  {
    title: "LinkedIn",
    iconName: "SiLinkedin",
    url: "https://www.linkedin.com/in/davidavikasis/",
    color: "#0077b5",
    tooltip: "Check out my LinkedIn profile",
  },
  {
    title: "Email",
    iconName: "SiGmail",
    url: "david@appandbeyond.com",
    color: "#d93025",
    copyToClipboard: true,
    tooltip: "Copy david@appandbeyond.com to your clipboard",
  },
  {
    title: "CV File",
    iconName: "HiDocumentArrowDown",
    file: {
      title: "David Avikasis - CV",
      url: "https://assets.ctfassets.net/wh2ajes7f2qa/6fEJAVxRoNpSJAGltZ9FVD/34d80b2dc1fcaaa77390faeb1fc01955/DavidAvikasisCV.pdf",
    } as any,
    color: "#d93025",
    // download: true,
    tooltip: "Download my CV as a PDF file",
  },
];

export const STACK_ITEMS: Partial<Queries.ContentfulStackItem>[] = [
  {
    title: "Javascript",
    iconName: "SiJavascript",
    color: "#fcdc00",
    metadata: {
      tags: [
        { name: "javascript" } as any,
        { name: "js" },
        { name: "frontend" },
        { name: "backend" },
        { name: "scripts" },
        { name: "scripting" },
        { name: "programming" },
        { name: "language" },
        { name: "code" },
        { name: "coding" },
        { name: "node.js" },
        { name: "node" },
        { name: "ES6" },
        { name: "ECMAScript" },
      ],
    },
  },
  {
    title: "TypeScript",
    iconName: "SiTypescript",
    color: "#007ad3",
    // keywords: [
    //   "javascript",
    //   "typescript",
    //   "ts",
    //   "js",
    //   "frontend",
    //   "scripts",
    //   "scripting",
    //   "programming",
    //   "language",
    //   "code",
    //   "coding",
    //   "node.js",
    //   "node",
    //   "ES6",
    //   "ECMAScript",
    // ],
  },
  {
    title: "HTML",
    iconName: "SiHtml5",
    color: "#f84200",
    // keywords: [
    //   "frontend",
    //   "language",
    //   "code",
    //   "coding",
    //   "html",
    //   "html5",
    //   "www",
    //   "web",
    //   "markup",
    // ],
  },
  {
    title: "CSS",
    iconName: "SiCss3",
    color: "#0074be",
    // keywords: [
    //   "frontend",
    //   "language",
    //   "code",
    //   "coding",
    //   "html",
    //   "css",
    //   "css3",
    //   "www",
    //   "web",
    //   "style",
    //   "styling",
    // ],
  },
  {
    title: "Python",
    iconName: "SiPython",
    color: "#244d6f",
    // keywords: [
    //   "python",
    //   "backend",
    //   "scripts",
    //   "scripting",
    //   "programming",
    //   "language",
    //   "code",
    //   "coding",
    // ],
  },
  {
    title: "Ruby",
    iconName: "SiRuby",
    color: "#df0000",
    // keywords: [
    //   "ruby",
    //   "backend",
    //   "scripts",
    //   "scripting",
    //   "programming",
    //   "language",
    //   "code",
    //   "coding",
    //   "rails",
    //   "rubyonrails",
    // ],
  },
  {
    title: "Ruby on Rails",
    iconName: "SiRubyonrails",
    color: "#df0000",
    // keywords: [
    //   "ruby",
    //   "rails",
    //   "backend",
    //   "scripts",
    //   "scripting",
    //   "rails",
    //   "rubyonrails",
    //   "framework",
    //   "activerecord",
    //   "api",
    //   "orm",
    //   "MVC",
    //   "Model-View-Controller",
    // ],
  },
  {
    title: "React.js",
    iconName: "SiReact",
    color: "#61dafb",
    // keywords: [
    //   "react.js",
    //   "react",
    //   "JavaScript",
    //   "frontend",
    //   "Web",
    //   "single page application",
    //   "spa",
    //   "Virtual DOM",
    //   "Components",
    //   "JSX",
    //   "React Native",
    //   "Redux",
    //   "Flux",
    //   "Webpack",
    //   "node.js",
    //   "ES6",
    //   "Babel",
    //   "Higher-order components",
    //   "HOC",
    //   "framework",
    // ],
  },
  {
    title: "Angular",
    iconName: "SiAngular",
    color: "#dd0031",
    // keywords: [
    //   "JavaScript",
    //   "TypeScript",
    //   "Dependency injection",
    //   "RxJS",
    //   "Observables",
    //   "frontend",
    //   "Web",
    //   "single page application",
    //   "spa",
    //   "Shadow DOM",
    //   "Components",
    //   "Webpack",
    //   "node.js",
    //   "ES6",
    //   "framework",
    // ],
  },
  {
    title: "Apollo GraphQL",
    iconName: "SiApollographql",
    color: "#3f20ba",
    // keywords: [
    //   "JavaScript",
    //   "GraphQL",
    //   "React",
    //   "React Native",
    //   "react.js",
    //   "frontend",
    //   "backend",
    //   "api",
    //   "Web",
    // ],
  },
  {
    title: "Redux",
    iconName: "SiRedux",
    color: "#764abc",
    // keywords: [
    //   "JavaScript",
    //   "React",
    //   "react.js",
    //   "frontend",
    //   "api",
    //   "Web",
    //   "store",
    //   "reducer",
    //   "state management",
    //   "middleware",
    //   "thunk",
    //   "RxJS",
    //   "Observables",
    //   "single source of truth",
    //   "flux",
    // ],
  },
  {
    title: "Gatsby",
    iconName: "SiGatsby",
    color: "#7026b8",
  },
  {
    title: "Tailwind CSS",
    iconName: "SiTailwindcss",
    color: "#06b6d4",
  },
  {
    title: "MySQL",
    iconName: "SiMysql",
    color: "#00758f",
  },
  {
    title: "PostgreSQL",
    iconName: "SiPostgresql",
    color: "#336791",
  },
  {
    title: "MongoDB",
    iconName: "SiMongodb",
    color: "#47a248",
  },
  {
    title: "Redis",
    iconName: "SiRedis",
    color: "#d82c20",
  },
  {
    title: "GraphQL",
    iconName: "SiGraphql",
    color: "#e535ab",
  },
  {
    title: "AWS",
    iconName: "SiAmazonaws",
    color: "#ff9600",
  },
  {
    title: "DigitalOcean",
    iconName: "SiDigitalocean",
    color: "#0080ff",
  },
  {
    title: "Microsoft Azure",
    iconName: "SiMicrosoftazure",
    color: "#0089d6",
  },
];
